name: smart_transport_tracker
description: A Flutter app for tracking school transport.
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_maps_flutter: ^2.9.0
  shared_preferences: ^2.3.2
  flutter_spinkit: ^5.2.1
  ionicons: ^0.2.2
  provider: ^6.0.0
  lottie: ^2.0.0
  location: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/vehicle_tracking.json
    - assets/animations/notifications.json
    - assets/animations/communication.json
    - assets/images/logo.png